### ISSUE TITLE
Errors running this example in Flink 1.3.2 !!

### ISSUE THREAD

**Issue by SyCode7** [tillrohrmann/cep-monitoring#11]
Hi I have tried to run this example  in Flink 1.3.2 but to no avail.  I am getting the error "The target type of this expression must be a functional interface" at line 84 of the CEPMonitoring class . There are also other e.g.  on line 103 (Type mismatch: cannot convert from TemperatureWarning to R) . Could you provide me some hints on what needs to be changed ?

**Comment by tillrohrmann** [comment]
Hi @SyCode7, I've pushed a commit which bumps the Flink version to 1.3.2. Due to a small regression we can no longer use a lambda expression for the where clause and thus I had to instantiate a `IterativeCondition` explicitly. In the future, this will be changed again.
