### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by rikenshah** [tillrohrmann/cep-monitoring#12]
This is not an issue, but rather I am asking for some instructions so as for how to run it. 

So far, I have tried, 
`java -cp "../cep-monitoring-1.0.jar" org.stsffap.cep.monitoring.CEPMonitoring` from classes folder and then many variations of the paths. I also tried importing in IntelliJ ide and building and running it. 

I am a newbie trying to learn Apache flink and CEP, any help would be appreciated.

**Comment by rikenshah** [comment]
I tried running flink first and then using flink to run the jar file, still gives no classdef found error

**Comment by tillrohrmann** [comment]
Hi @rikenshah, you can run the program by running `mvn exec:java -Dexec.mainClass=org.stsffap.cep.monitoring.CEPMonitoring`.

Alternatively, you can run the job from within your IDE by executing the `main` method. Or you start a Flink cluster and submit the jar. You can find information about how to do it [here](https://ci.apache.org/projects/flink/flink-docs-release-1.4/quickstart/setup_quickstart.html#quickstart).

**Comment by rikenshah** [comment]
Thank you so much. I also followed [these](https://stackoverflow.com/questions/48919313/java-noclassdeffounderror-apache-flink-complex-event-processing/48936754#48936754) steps to run it.
