### ISSUE TITLE
Throwing Invalid Types Exception

### ISSUE THREAD

**Issue by mrakshay** [tillrohrmann/cep-monitoring#2]
I am trying to execute the code but it is throwing following Exception :  org.apache.flink.api.common.functions.InvalidTypesException: Input mismatch: POJO type 'org.stsffap.cep.monitoring.events.MonitoringEvent' expected but was 'java.util.Map'. at line 67

Line 67 is as follows:

```
DataStream<TemperatureWarning> warnings = tempPatternStream.select(
            (Map<String, MonitoringEvent> pattern) -> {
                TemperatureEvent first = (TemperatureEvent) pattern.get("first");
                TemperatureEvent second = (TemperatureEvent) pattern.get("second");

                return new TemperatureWarning(first.getRackID(), (first.getTemperature() + second.getTemperature()) / 2);
            }
        );
```

I am not able to get the error,.....what is the solution for this ??

**Comment by tillrohrmann** [comment]
How did you build the program? Did you simply clone the repository and ran `mvn clean package`? Or did you change anything?

**Comment by mrakshay** [comment]
No, I didn't change anything special...i just cloned the repository,imported the project in Eclipse & just updated the project as Maven -> Update Project & ran **mvn clean package**....

**Comment by tillrohrmann** [comment]
Have you tried building the project via maven on the command line?

**Comment by mrakshay** [comment]
I tried building this project via `mvn clean install` on Amazon EC2 where I installed openjdk 1.8...I placed the jar on EC2 & ran the command by going into the flink directory **./bin/flink run /pathtojar/CEP-Monitoring.jar org.stsffap.cep.monitoring.CEPMonitoring** & it threw the following exception : 
*\* The program finished with the following exception:

**The generic type parameters of 'Map' are missing.
It seems that your compiler has not stored them into the .class file.
Currently, only the Eclipse JDT compiler preserves the type information necessary to use the lambdas feature type-safely.
See the documentation for more information about how to compile jobs containing lambda expressions.
        org.apache.flink.api.java.typeutils.TypeExtractor.validateLambdaGenericParameter(TypeExtractor.java:1316)
        org.apache.flink.api.java.typeutils.TypeExtractor.validateLambdaGenericParameters(TypeExtractor.java:1302)
        org.apache.flink.api.java.typeutils.TypeExtractor.getUnaryOperatorReturnType(TypeExtractor.java:346)
        org.apache.flink.cep.PatternStream.select(PatternStream.java:64)
        org.stsffap.cep.monitoring.CEPMonitoring.main(CEPMonitoring.java:95)  ****

 Is there any specific way to compile Flink programs for Java 8 related to Lambda expressions ?? What is the solution for this ??

**Comment by tillrohrmann** [comment]
The pom file should contain the following section

```
<plugin>
    <!-- Use compiler plugin with tycho as the adapter to the JDT compiler. -->
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        <source>1.8</source>
        <target>1.8</target>
        <compilerId>jdt</compilerId>
    </configuration>
    <dependencies>
        <!-- This dependency provides the implementation of compiler "jdt": -->
        <dependency>
            <groupId>org.eclipse.tycho</groupId>
            <artifactId>tycho-compiler-jdt</artifactId>
            <version>0.21.0</version>
        </dependency>
    </dependencies>
</plugin>
```

This should make sure that the Eclipse compiler is used and thus maintaining the type information. Have you changed the original pom file?

**Comment by mrakshay** [comment]
Thanks @tillrohrmann ...that solution worked for me...

**Comment by tillrohrmann** [comment]
Good to hear :-)

**Comment by mrakshay** [comment]
@tillrohrmann : Can you please provide a help doc or Readme file ...An example or demo regarding how to run this application ?? I am still not getting this application...if you could please share any demo or steps to run the application....  Thank You

**Comment by tillrohrmann** [comment]
Running it from the command line via: `mvn clean package exec:java -Dexec.mainClass="org.stsffap.cep.monitoring.CEPMonitoring"`

You can also import it in your IDE and then run it from within your IDE. Note that in IntelliJ you have to use the Eclipse compiler.

You can also submit the packaged jar to a flink cluster via `bin/flink -p PARALLELISM JAR-FILE`. See [this link](https://ci.apache.org/projects/flink/flink-docs-release-1.0/apis/cli.html) for more information.

**Comment by mrakshay** [comment]
Do I need to have a event stream like Kafka to consume the data ?? I want to know what data source are you using for this application ??

**Comment by tillrohrmann** [comment]
No you don't. The program comes with its own data source which generates random data.

**Comment by mrakshay** [comment]
I tried created a packaged jar & submitted that jar to flink cluster but I cannot see any data generated...I kept the application running for 90 mins...but there wasn't any data coming...As a result,no alerts & warnings were printed.... 
![flink](https://cloud.githubusercontent.com/assets/15104286/15141259/d1dc0c30-16bc-11e6-8d11-9972c9bf9cd9.PNG)

**Comment by tillrohrmann** [comment]
If you submit the job to the cluster, the results are not printed to your
console. Instead you will find the stdout output in the taskmanager.out
files which are accessible from the web dashboard (under TaskManagers -->
Stdout) or which you can find in the FLINK_HOME/log directory.

**Comment by mrakshay** [comment]
Thanks @tillrohrmann ...it worked

**Comment by mrakshay** [comment]
Hello @tillrohrmann . One question which arises here is that you have made one single application which does the work of Pattern Matching or CEP....You didn't use any streaming layer in between like Kafka or any...I just want to know why you didn't use any streaming layer in between ?? Also,I want to know whether how this application will execute if I put a streaming layer in between ? Thank You
