### ISSUE TITLE
Seeking explanation for Flink Window Time Concept used in this cep-monitoring

### ISSUE THREAD

**Issue by mrakshay** [tillrohrmann/cep-monitoring#4]
I am finding it very confusing as I am not getting the window time concept in this application..We are doing comparisons here..i.e. **(Two consecutive temperature events whose temperature is higher than the given threshold appearing within a time interval of 10 seconds) &  (Generating a temperature alert only iff the second temperature warning's average temperature is higher than first warning's temperature).** I want to know whether we are doing comparison on entire batch of data or data which is  streaming/appearing within window time (i.e. 10 or 20 seconds) ?? How this will work in distributed mode ?? For the sake of understanding I just changed the code : 
`if (first.getAverageTemperature() < second.getAverageTemperature()) {
                    out.collect(new TemperatureAlert(second.getRackID(),second.getAverageTemperature(),second.getTimeStamp()));
                }`
   ... I have attached output files of flink cep execution on 1 master & 3 cores...It would be quite helpful if you explain out how this window time concept works here...Thank You ...
![flink3](https://cloud.githubusercontent.com/assets/15104286/15545651/bad96d0c-22ba-11e6-861b-aa158280b6a2.PNG)
![flink1](https://cloud.githubusercontent.com/assets/15104286/15545650/bad16de6-22ba-11e6-8f22-485fe970b8a4.PNG)
![flink2](https://cloud.githubusercontent.com/assets/15104286/15545652/badae61e-22ba-11e6-9698-20e1566ad5f1.PNG)

**Comment by tillrohrmann** [comment]
Time windows in CEP basically say when events can be discarded, because they're no longer needed for further matchings. That is exactly when the window time interval has passed by. In your case, a temperature warning is only generated if the system detects two events with a temperature higher than the threshold value which appear within a time interval of 10 seconds.

CEP is parallelized by keying the input stream by a key. In the example, it is the rack ID on which we key. Then every subset of stream events which have the same rack ID can be treated independently.

**Comment by mrakshay** [comment]
If we notice in the files,some of the alerts are getting generated for the temperature warnings which are not present in the current file...Are these records coming in batches ?? What might be the reason for the temperature warnings not present in current file ??

**Comment by tillrohrmann** [comment]
Could you tell me the lines which are supposedly wrong?

**Comment by mrakshay** [comment]
I ran the program in distributed mode with 1 master & 3 cores..In all 3 files,the data gets distributed i.e. 1 file has records of 2 rackIDs,another has records of 5 rackIDs & another file has records of other rackIDs..Hence I share one of the files which has printed the following output: 

> TemperatureAlert(4), For Temperature:110.60808293330018,At Timestamp : 1464259424016
> TemperatureAlert(4), For Temperature:102.75469017603604,At Timestamp : 1464259486205
> TemperatureAlert(4), For Temperature:110.98650912782037,At Timestamp : 1464259492214
> TemperatureAlert(4), For Temperature:115.47245702561352,At Timestamp : 1464259554901
> TemperatureAlert(1), For Temperature:113.65291115679136,At Timestamp : 1464259735252
> TemperatureAlert(1), For Temperature:110.88374917920495,At Timestamp : 1464259795436
> TemperatureAlert(1), For Temperature:116.23995588293668,At Timestamp : 1464259810056
> TemperatureAlert(4), For Temperature:103.27459440260448,At Timestamp : 1464259929121
> TemperatureAlert(1), For Temperature:114.53029859331343,At Timestamp : 1464259942139
> TemperatureAlert(4), For Temperature:109.13921010205338,At Timestamp : 1464260060204
> (4,117.14184470661019) ,1464259692594
> TemperatureWarning(4,115.08289903597866) ,1464259701806
> TemperatureWarning(4,113.9136297471108) ,1464259723436
> TemperatureWarning(1,112.15684481878216) ,1464259733249
> TemperatureWarning(1,113.65291115679136) ,1464259735252
> TemperatureWarning(1,125.07387226846537) ,1464259770401
> TemperatureWarning(1,100.829623781131) ,1464259776409
> TemperatureWarning(4,105.76155716070109) ,1464259789027
> TemperatureWarning(1,110.88374917920495) ,1464259795436
> TemperatureWarning(1,110.03271176117211) ,1464259803447
> TemperatureWarning(1,108.99904165096143) ,1464259809255
> TemperatureWarning(1,116.23995588293668) ,1464259810056
> TemperatureWarning(1,113.74475027506949) ,1464259815664
> TemperatureWarning(4,118.65623814713382) ,1464259826078
> TemperatureWarning(1,125.24779125130385) ,1464259877349
> TemperatureWarning(4,110.38935504983476) ,1464259890467
> TemperatureWarning(4,101.92222208289115) ,1464259927319
> TemperatureWarning(4,103.27459440260448) ,1464259929121
> TemperatureWarning(1,113.15048106140453) ,1464259937533
> TemperatureWarning(1,114.53029859331343) ,1464259942139
> TemperatureWarning(4,112.4172409140119) ,1464259953755
> TemperatureWarning(1,107.21833971444117) ,1464259981194
> TemperatureWarning(1,105.08408728033956) ,1464259981594
> TemperatureWarning(4,108.83063471822507) ,1464259990608
> TemperatureWarning(4,127.9723904319025) ,1464260054997
> TemperatureWarning(4,106.06561268720989) ,1464260059804
> TemperatureWarning(4,109.13921010205338) ,1464260060204
> TemperatureWarning(4,124.68997753475641) ,1464260093250

Start looking from line number 5. You can check that all alerts that have been printed from line number 5 (i.e. for temperature : 113.65291115679136),we can identify the temperatures below (Temperature : 113.65291115679136 is present at line 15) in **TemperatureWarning** meaning which we can identify for which temperatures,the alerts have been printed....but what about the alerts generated from line number 1 to 4 ?? You can even find the same for record in line no. 11.. I mean how we can identify that for which TemperatureWarnings that alerts have been generated ??  Is it performing streaming in **batch-mode , continuous or micro-batch mode** ??
