### ISSUE TITLE
Requirement of Streaming layer in between

### ISSUE THREAD

**Issue by mrakshay** [tillrohrmann/cep-monitoring#5]
Hello @tillrohrmann . One question which arises here is that you have made one single application which does the work of Pattern Matching or CEP. (Like ingest & process is done by 1 application)...You didn't use any streaming layer in between like Kafka or any...I just want to know why you didn't use any streaming layer in between the producer & the consumer?? Also,I want to know what will be the advantages and disadvantages if I put a streaming layer in between ?? Thank You

**Comment by tillrohrmann** [comment]
You can plug in any other streaming source if you want to (including Kafka). But for the purpose of demonstrating the CEP application I've created a self-contained source which generates the input data. This makes it easier to run the job, because you don't have to set up a Kafka cluster.

**Comment by mrakshay** [comment]
You are right that an overhead of setting up Kafka cluster isn't needed if we use self-contained source..I do get the scenario that if I need to use Kafka then I need to write  2 applications & also monitor these 2 applications.But I am still not getting why you created just a single application...Could you please just elaborate ??

**Comment by tillrohrmann** [comment]
The input data is generated in the same program which also runs the CEP operators. That's why you don't need two programs.

**Comment by mrakshay** [comment]
Yes right & hence your application becomes very optimized...but what was the reason of not using a streaming layer in between ?? I mean if you have used any streaming layer,then that could have given you advantage of collecting & processing data in real-time...so just want to know why streaming layer was not used in your application??

**Comment by tillrohrmann** [comment]
What do you mean with streaming layer? Why do you want to use such a streaming layer? What other advantage than re-playability of your stream are you referring to?

**Comment by mrakshay** [comment]
Ok @tillrohrmann .. At the end, I just want to know that when the need will arise to use Kafka or Kinesis?? If I use Kafka or Kinesis in between,will I get any advantage ??

**Comment by tillrohrmann** [comment]
Only partial re-playability of your data in case of recovery. But the program is a toy example. So in reality you would always have a data ingestion system from which you read your data.

**Comment by mrakshay** [comment]
Ok...thanks a lot @tillrohrmann ....Thanks for the help
