### ISSUE TITLE
Use of Event Time in Pattern/Pattern Stream API

### ISSUE THREAD

**Issue by mrakshay** [tillrohrmann/cep-monitoring#6]
Hello @tillrohrmann ...I am trying to get the use of Event Time..What I have read is that Event Time is the time when event (data) gets generated at source.How this Event Time works with Pattern API or the Pattern Stream API?? I want to know what will happen if I change Time Characteristic from Event Time to Ingestion Time or Processing Time ??

**Comment by tillrohrmann** [comment]
Flink's CEP implementation can handle all three time characteristics: Event time, ingestion time and processing time. Depending on the defined time characteristic, the incoming events are processed according to their event time or the processing time. The former can of course entail a buffering and reordering of elements if they arrived out of order.

**Comment by mrakshay** [comment]
But why was Event Time was used in your example ??  And I want to know whether the Time Characteristic has any relation to Pattern API ??

**Comment by tillrohrmann** [comment]
The time characteristic has no effect on the pattern API. The example uses ingestion time because you want to reason about events with respect to their event time/time they entered the system and not the processing time which is influenced by external factors such as CPU load, network, etc.

**Comment by mrakshay** [comment]
Oh..ok... 
![i1](https://cloud.githubusercontent.com/assets/15104286/16068022/d0575f7e-32df-11e6-9a98-b01c28c02cc8.PNG)

I can see that,you have put the Stream time characteristic  as "Event Time" but when it is entering Flink i.e. in the DataStream you are assigning "Ingestion Time"....What does this mean ?? What is the difference between the two of them ??

**Comment by tillrohrmann** [comment]
https://ci.apache.org/projects/flink/flink-docs-master/apis/streaming/event_time.html

**Comment by mrakshay** [comment]
While entering Flink,"IngestionTime" has been set..what exactly is happening on these 2 lines ?? If the example uses ingestion time,why was the need to set "Event Time" ??
